- src/components/picker-view/index.ios.js
- src/components/picker-view/index.web.js
> fix(Picker): add type transfer for selectedValue

- example/src/scenes/Stepper/index.js
- src/components/stepper/__tests__/__snapshots__/stepper.test.js.snap
- src/components/stepper/index.js
> feat(Stepper): add opacity in disabale

- src/components/i18n/strings.js
Fix typos in local multilingual.
> wip(strings): modify strings

- src/components/notification/index.js
- src/components/notification/styled.js
Fix the misalignment of text and Icon in the notification status bar component on Android, fixes #63.
> fix(Notifacation): fix text and Icon misalignment on Android, fixes #63

- src/components/popup/__tests__/__snapshots__/countdown.test.js.snap
- src/components/popup/__tests__/__snapshots__/custom.test.js.snap
- src/components/popup/__tests__/__snapshots__/date-picker.test.js.snap
- src/components/popup/__tests__/__snapshots__/list.test.js.snap
- src/components/popup/__tests__/__snapshots__/number-selector.test.js.snap
- src/components/popup/__tests__/__snapshots__/picker.test.js.snap
- src/components/popup/__tests__/__snapshots__/timer-picker.test.js.snap
- src/components/popup/styled.js
- src/components/popup/withSkeleton.js
> style(Popup): fit style to UI

- packages/tuya-panel-kit/package.json
- packages/tuya-panel-theme/package.json
> fix(kit): add dependencies

- example/yarn.lock
- packages/tuya-panel-kit/src/components/popup/__tests__/__snapshots__/timer-picker.test.js.snap
- packages/tuya-panel-kit/src/components/timer-picker/__tests__/__snapshots__/timer-picker.test.js.snap
- packages/tuya-panel-kit/src/components/timer-picker/index.js
TimerPicker font is cut off in some IOS.
> fix(TimerPicker): TimerPicker font is cut off in some IOS

- example/src/pages/navigation/top-bar/index.tsx
- example/src/pages/presentation/linear-gradient/index.tsx
- example/src/pages/presentation/radial-gradient/index.tsx
- example/yalc.lock
- example/yarn.lock
fit example in Android and IOS.
> docs(kit): fit example in android and ios

- .github/workflows/preview-build.yml
> fix(ci): pages deps

- .github/workflows/preview-build.yml
> fix: pages ci

- .github/workflows/gh-pages.yml
- .github/workflows/preview-build.yml
- example/.umirc.ts
> fix(preview-ci): ci preview build env fixed

- example/src/main.tsx
- packages/tuya-panel-kit/src/components/layout/react-navigation/index.js
> feat(Navigation): export navgationRef

- example/yarn.lock
- src/components/layout/offline-view/ble-offline-view/index.js
- src/components/webview/index.js
delete some Sensitive Information.
> perf(bleOffline): change bleOffline to multi-region --- 2.x

- example/yarn.lock
- src/components/layout/offline-view/index.js
- src/components/webview/index.js
- src/utils/core.js
- yarn.lock
hide sensitive information of bleOffline.
> perf(bleOffline): change bleOfflineLink to multi-region ---- 1.x

- example/yarn.lock
- packages/tuya-panel-kit/src/components/webview/index.js
set source to isRequired in WebView.
> chore(webview): set source to isRequired in WebView

- .github/workflows/gh-pages.yml
> fix(pages-ci): fix env

- packages/tuya-panel-kit/src/components/layout/react-navigation/index.js
> fix(NavigationContainer): fix onBack of TopBar

- example/tuya-components-styled/.umirc.ts
- example/tuya-panel-kit/.umirc.ts
> fix: examples cdn

- packages/tuya-panel-kit/src/components/timer-picker/index.js
- packages/tuya-panel-kit/src/components/timer-picker/utils.js
Please provide a brief summary of the changes. If it is related to an issue, please bring the issue number, like `fixes #${number}`.
> feat(TimerPicker): add amText and pmText to support custom

- packages/tuya-panel-kit/src/components/i18n/strings.js
> docs(bleOffline): add i18n of bleOffline

- src/components/layout/offline-view/ble-offline-view/index.js
fix requireNativeComponent crash.
> fix(bleOffline): fix requireNativeComponent crash

- example/tuya-components-styled/src/components/block-view.tsx
- example/tuya-components-styled/src/components/list-view.tsx
- example/tuya-panel-kit/src/components/block-view.tsx
- example/tuya-panel-kit/src/components/list-view.tsx
- example/tuya-panel-kit/src/i18n/strings.ts
- example/tuya-panel-kit/src/layouts/index.tsx
- example/tuya-panel-kit/src/pages/basic/slider-progress/index.tsx
- example/tuya-panel-kit/src/pages/data-entry/slider/index.tsx
- example/tuya-panel-kit/src/pages/feedback/swipeout/index.tsx
- example/tuya-panel-kit/src/pages/navigation/tab-bar/index.tsx
- example/tuya-panel-kit/src/pages/navigation/tab/index.tsx
- example/tuya-panel-kit/src/pages/navigation/tabs/index.tsx
- example/tuya-panel-kit/src/pages/navigation/top-bar/index.tsx
- example/tuya-panel-kit/src/pages/presentation/carousel/index.tsx
- example/tuya-panel-kit/src/pages/presentation/divider/index.tsx
- example/tuya-panel-kit/src/pages/presentation/radial-gradient/index.tsx
- example/tuya-panel-kit/src/pages/presentation/tylist-item/index.tsx
- example/tuya-panel-kit/yalc.lock
fix styled
- [v] This change requires a documentation update
> fix: styles

- example/tuya-panel-kit/yarn.lock
- packages/tuya-panel-kit/src/components/popup/__tests__/__snapshots__/number-selector.test.js.snap
- packages/tuya-panel-kit/src/components/popup/number-selector.js
> feat(Popup.numberSelector): add valueStyle

- example/tuya-panel-kit/yarn.lock
- packages/tuya-panel-kit/src/components/swipeout/swipeout.js
Based on the original Swipeout add event onScrollEnd
> (feature/tuya-panel-kit-sophia):swipeout add onScrollEnd

- example/tuya-components-styled/src/pages/basic/button/index.tsx
- example/tuya-components-styled/src/pages/enum/button-card/index.tsx
- example/tuya-components-styled/src/pages/enum/enum-card/index.tsx
- example/tuya-components-styled/src/pages/enum/enum-slider-card/index.tsx
- example/tuya-components-styled/src/pages/enum/enum-tabs-button-card/index.tsx
- example/tuya-components-styled/src/pages/number/slider-card/index.tsx
Please provide a brief summary of the changes. If it is related to an issue, please bring the issue number, like `fixes #${number}`.
> chore: demo Chinese

- example/tuya-panel-kit/package.json
- example/tuya-panel-kit/src/pages/animation/diffusion/index.tsx
- example/tuya-panel-kit/src/pages/animation/wave/index.tsx
- example/tuya-panel-kit/yarn.lock
- packages/tuya-panel-kit/package.json
- packages/tuya-panel-kit/src/index.js
add wave、diffusion、drawer to kit.
> feat(kit): add wave、diffusion、drawer to kit

- packages/tuya-panel-theme/src/core.ts
- packages/tuya-panel-utils/src/theme/utils.ts
Fixed crashes where the theme is not Light or Dark.
> fix(theme): Fixed crashes where the theme is not Light or Dark

- example/tuya-panel-kit/yalc.lock
- example/tuya-panel-kit/yarn.lock
- packages/tuya-panel-kit/src/components/modal/TYModal.js
- packages/tuya-panel-kit/src/components/modal/__tests__/__snapshots__/TYModal.test.js.snap
fix(Modal): Fixed an issue with Popup and Dialog combining content overlay on Android, fixed #158.
> fix(Modal): Fixed an issue with Popup and Dialog combining content overlay on Android, fixed #158

- packages/tuya-panel-kit/src/components/layout/navigator-layout/index.js
- packages/tuya-panel-kit/src/components/layout/react-navigation/index.js
- packages/tuya-panel-layout/src/navigator-layout/index.tsx
- packages/tuya-panel-layout/src/react-navigation/index.tsx
- packages/tuya-panel-layout/src/react-navigation/interface.ts
fix(Notification): Fixed an issue where Notification was automatically destroyed in the background, fixed #159.
> fix(Notification): Fixed an issue where Notification was automatically destroyed in the background, fixed #159

- packages/tuya-panel-theme/src/core.ts
- packages/tuya-panel-utils/src/theme/utils.ts
fix(Dialog && Popup): fix theme = basic in Dialog or Popup.
> fix(Dialog && Popup): fix theme = basic in Dialog or Popup

- packages/tuya-panel-tabbar/src/__tests__/__snapshots__/index.test.js.snap
- packages/tuya-panel-tabbar/src/index.tsx
- packages/tuya-panel-tabbar/src/interface.ts
> feat(TabBar): add scrollEnabled props

- packages/tuya-panel-radial-gradient/README.md
- packages/tuya-panel-radial-gradient/jest.config.js
- packages/tuya-panel-radial-gradient/package.json
- packages/tuya-panel-radial-gradient/src/__tests__/__snapshots__/index.test.js.snap
- packages/tuya-panel-radial-gradient/src/__tests__/index.test.js
- packages/tuya-panel-radial-gradient/src/index.tsx
- packages/tuya-panel-radial-gradient/src/interface.ts
- packages/tuya-panel-radial-gradient/tsconfig.json
> feat(RadialGradient): RadialGradient

- packages/tuya-panel-kit/src/components/layout/api/index.js
- packages/tuya-panel-kit/src/components/layout/offline-view/ble-offline-view/index.js
- packages/tuya-panel-kit/src/components/layout/offline-view/index.js
- packages/tuya-panel-kit/src/components/layout/offline-view/new-offline-view.js
The offline jump link was changed to the knowledge base H5 link.
> feat(ble): The offline jump link was changed to the knowledge base H5 link

- packages/tuya-panel-kit/src/components/layout/api/index.js
- packages/tuya-panel-kit/src/components/layout/offline-view/ble-offline-view/index.js
- packages/tuya-panel-kit/src/components/layout/offline-view/index.js
- packages/tuya-panel-kit/src/components/layout/offline-view/new-offline-view.js
Reverts tuya/tuya-panel-kit#167
> Revert "feat(ble): The offline jump link was changed to the knowledge base H5 link"

- packages/tuya-panel-kit/src/components/dialog/__tests__/__snapshots__/prompt.test.js.snap
- packages/tuya-panel-kit/src/components/dialog/prompt.js
- packages/tuya-panel-kit/src/components/dialog/styled.js
- packages/tuya-panel-kit/src/components/dialog/withMotion.js
> feat(Prompt): animation optimization

- example/tuya-panel-kit/src/pages/basic/motion/index.tsx
- packages/tuya-panel-motion/README.md
- packages/tuya-panel-motion/jest.config.js
- packages/tuya-panel-motion/package.json
- packages/tuya-panel-motion/src/__tests__/__snapshots__/fade.test.js.snap
- packages/tuya-panel-motion/src/__tests__/__snapshots__/pull-up.test.js.snap
- packages/tuya-panel-motion/src/__tests__/__snapshots__/push-down.test.js.snap
- packages/tuya-panel-motion/src/__tests__/__snapshots__/scale-fade-in.test.js.snap
- packages/tuya-panel-motion/src/__tests__/__snapshots__/scale-pull-down.test.js.snap
- packages/tuya-panel-motion/src/__tests__/__snapshots__/toast.test.js.snap
- packages/tuya-panel-motion/src/__tests__/fade.test.js
- packages/tuya-panel-motion/src/__tests__/pull-up.test.js
- packages/tuya-panel-motion/src/__tests__/push-down.test.js
- packages/tuya-panel-motion/src/__tests__/scale-fade-in.test.js
- packages/tuya-panel-motion/src/__tests__/scale-pull-down.test.js
- packages/tuya-panel-motion/src/__tests__/toast.test.js
- packages/tuya-panel-motion/src/constant.ts
- packages/tuya-panel-motion/src/fade.tsx
- packages/tuya-panel-motion/src/index.tsx
- packages/tuya-panel-motion/src/interface.ts
- packages/tuya-panel-motion/src/pull-up.tsx
- packages/tuya-panel-motion/src/push-down.tsx
- packages/tuya-panel-motion/src/scale-fade-in.tsx
- packages/tuya-panel-motion/src/scale-pull-down.tsx
- packages/tuya-panel-motion/src/toast.tsx
- packages/tuya-panel-motion/tsconfig.json
> feat(Motion): tuya-panel-motion

- packages/tuya-panel-theme/src/base.ts
> fix(global): fix confict of global

- example/tuya-components-styled/src/pages/bool/switch-card/index.tsx
- packages/tuya-panel-style-switch-card/package.json
- packages/tuya-panel-style-switch-card/src/__tests__/__snapshots__/index.test.js.snap
- packages/tuya-panel-style-switch-card/src/__tests__/index.test.js
- packages/tuya-panel-style-switch-card/src/index.tsx
- packages/tuya-panel-style-switch-card/src/interface.ts
- packages/tuya-panel-switch/src/index.tsx
- packages/tuya-panel-switch/src/interface.ts
- packages/tuya-panel-switch/src/switch.tsx
Fixed Switch controlled and borderRadius.
> fix(Switch): fixed Switch controlled and borderRadius

- packages/tuya-panel-kit/src/components/dialog/withMotion.js
- packages/tuya-panel-kit/src/components/popup/withSkeleton.js
Optimize the order of asynchronous events.
> perf(Popup && Dialog): Optimize the order of asynchronous events

- packages/tuya-panel-icon/src/svg/index.tsx
- packages/tuya-panel-kit/src/components/TYLists/__tests__/__snapshots__/list.test.js.snap
- packages/tuya-panel-kit/src/components/checkbox/__tests__/__snapshots__/checkbox.test.js.snap
- packages/tuya-panel-kit/src/components/iconfont/svg/index.js
IconFont supports multi-path icon adaptation.
> feat(IconFont): IconFont supports multi-path icon adaptation

- example/tuya-components-styled/README.md
- example/tuya-panel-kit/README.md
> chore(example): update README.md

- packages/tuya-panel-tabs/src/tab-content.tsx
Fixed a mismatch between the Tabs component title and content.
> fix(Tabs): Fixed a mismatch between the Tabs component title and content
